CREATE TABLE versions (
  id SERIAL PRIMARY KEY,
  created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
  deleted_at TIMESTAMP WITHOUT TIME ZONE,
  version_id INTEGER NOT NULL,
  repository_id INTEGER NOT NULL
);

ALTER TABLE versions
ADD CONSTRAINT fk_repository
FOREIGN KEY (repository_id)
REFERENCES repositories(id)
ON DELETE CASCADE;

